#!/bin/bash
set -x
pip install --require-hashes -r requirements.txt --target ./package
pip install --no-deps --target ./package .
cp ./configuration/exodus-lambda-deploy.yaml ./package
scripts/mk-config > ./package/lambda_config.json
ls -al .
echo $EXODUS_LAMBDA_VERSION
aws cloudformation package \
	--template ./package/exodus-lambda-deploy.yaml \
	--s3-bucket $PROJECT-pipeline-artifacts \
	--output-template-file ./package/exodus-lambda-pkg.yaml
